source 'https://rubygems.org'

ruby '3.2.10'

gem 'rails', '~> 7.1.0'
gem 'pg', '~> 1.5'
gem 'puma', '~> 6.4'
gem 'bcrypt', '~> 3.1.7'
gem 'jwt'
gem 'rack-cors'
gem 'redis'
gem 'kaminari'

group :development, :test do
  gem 'debug', platforms: %i[ mri mingw x64_mingw ]
end

gem 'tzinfo-data', platforms: %i[ mingw mswin x64_mingw jruby ]
gem 'bootsnap', require: false